### ISSUE TITLE
Problem with 'AddEncounterConstraintMover'

### ISSUE THREAD

**Issue by jskim217** [Graylab/AlphaRED#2]
Hello, I'm a post-doc working at the academy.
I'm trying to run a local protein-protein docking using replica exchange methods.
When I ran the method, I received the following error message:

[FILE]: src/protocols/rosetta_scripts/RosettaScriptsParser.cc
[LINE]: 1207
[START_MESSAGE]
Input rosetta scripts XML file "dock.xml" failed to validate against the rosetta scripts schema. Use the option -parser::output_schema <output filename> to output the schema to a file to see all valid options.
Your XML has failed validation.  The error message below will tell you where in your XML file the error occurred.  Here's how to fix it:

1) If the validation fails on something obvious, like an illegal attribute due to a spelling error (perhaps you used scorefnction instead of scorefunction), then you need to fix your XML file.
2) If you haven't run the XML rewriter script and this might be pre-2017 Rosetta XML, run the rewriter script (tools/xsd_xrw/rewrite_rosetta_script.py) on your input XML first.  The attribute values not being in quotes (scorefunction=talaris2014 instead of scorefunction="talaris2014") is a good indicator that this is your problem.
3) If you are a developer and neither 1 nor 2 worked - email the developer's mailing list or try Slack.
4) If you are an academic or commercial user - try the Rosetta Forums https://www.rosettacommons.org/forum

Error messages were:
From line 18:
Error: Element 'AddEncounterConstraintMover': This element is not expected.

I was wondering if you could make it available to the public.
Also, could you provide the scoring weight muds_2021 described in Plos computational biology paper?
Looking forward to hearing from you.

**Comment by AmeyaHarmalkar** [comment]
Hi,
Seems like the mover is available in the developer release but not in the public version. I have commented it out for now but it might be included in the upcoming releases. Apologies for the inconvenience!
Also included the `muds_2021.wts` weights file in the `global_docking` directory

**Comment by jskim217** [comment]
Hello Ameya,

Thanks for updating.

Best regards,
Jisun Kim
ᐧ

2023년 12월 16일 (토) 오후 6:28, Ameya Harmalkar ***@***.***>님이 작성:

**Comment by youngh81** [comment]
I still had this problem even I use the updated script and mud_2021.wts, thanks.
